import React, { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ShieldCheck } from "lucide-react";
import { ITENS_CHECKLIST_EXTINTOR_MENSAL, listarExtintoresVistoria, salvarInspecaoExtintor } from "../../services/extintoresVistoriaService";

export function VistoriaExtintorPublica({ token = "" }) {
    const extintor = useMemo(() => listarExtintoresVistoria().find((item) => item.tokenQr === token), [token]);
    const [respostas, setRespostas] = useState({});
    const [observacoes, setObservacoes] = useState("");
    const [enviado, setEnviado] = useState(false);
    if (!extintor) return <div className="flex min-h-screen items-center justify-center bg-slate-100 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-7 text-center shadow-sm"><AlertTriangle className="mx-auto text-amber-500" size={40} /><h1 className="mt-3 text-xl font-black text-slate-950">Equipamento não encontrado</h1><p className="mt-2 text-sm text-slate-500">Este QR Code não está vinculado a um extintor disponível.</p></div></div>;
    function enviar() { salvarInspecaoExtintor({ extintorId: extintor.id, codigo: extintor.codigo, competencia: new Date().toISOString().slice(0, 7), respostas, observacoes, responsavel: "Vistoria via QR Code", status: Object.values(respostas).includes("nao_conforme") ? "Atenção" : "Conforme" }); setEnviado(true); }
    return <main className="min-h-screen bg-slate-100 p-4"><div className="mx-auto max-w-xl space-y-4"><header className="rounded-2xl bg-slate-950 p-5 text-white shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-white/10 p-3"><ShieldCheck size={24} /></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-cyan-300">SafeScan Brasil</p><h1 className="mt-1 text-xl font-black">Vistoria de extintor</h1></div></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><span className="block text-xs text-slate-400">Equipamento</span><strong>{extintor.codigo}</strong></div><div><span className="block text-xs text-slate-400">Tipo</span><strong>{extintor.tipo} · {extintor.capacidade}</strong></div><div><span className="block text-xs text-slate-400">Ponto</span><strong>{extintor.ponto}</strong></div><div><span className="block text-xs text-slate-400">Localização</span><strong>{extintor.localizacao}</strong></div></div></header>{enviado ? <section className="rounded-2xl border border-emerald-200 bg-white p-8 text-center shadow-sm"><CheckCircle2 className="mx-auto text-emerald-600" size={46} /><h2 className="mt-3 text-xl font-black text-slate-950">Vistoria registrada</h2><p className="mt-2 text-sm text-slate-500">O resultado deste equipamento foi salvo com sucesso.</p></section> : <section className="rounded-2xl bg-white p-4 shadow-sm"><h2 className="font-black text-slate-950">Conferência mensal</h2><p className="mt-1 text-sm text-slate-500">Marque cada item conforme a situação encontrada.</p><div className="mt-4 space-y-2">{ITENS_CHECKLIST_EXTINTOR_MENSAL.map((item) => <div key={item.id} className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="text-sm font-semibold text-slate-700">{item.label}</p><div className="mt-2 flex gap-2"><Resposta ativo={respostas[item.id] === "conforme"} tipo="ok" onClick={() => setRespostas((atual) => ({ ...atual, [item.id]: "conforme" }))}>Conforme</Resposta><Resposta ativo={respostas[item.id] === "nao_conforme"} tipo="alerta" onClick={() => setRespostas((atual) => ({ ...atual, [item.id]: "nao_conforme" }))}>Atenção</Resposta></div></div>)}</div><label className="mt-4 block text-xs font-bold text-slate-600">Observações<textarea value={observacoes} onChange={(evento) => setObservacoes(evento.target.value)} rows={3} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="Descreva algo encontrado" /></label><button type="button" onClick={enviar} className="mt-4 w-full rounded-xl bg-sky-600 px-4 py-3 font-bold text-white">Enviar vistoria</button></section>}</div></main>;
}

function Resposta({ ativo, tipo, onClick, children }) { return <button type="button" onClick={onClick} className={`rounded-lg px-3 py-2 text-xs font-bold ring-1 ${ativo ? tipo === "ok" ? "bg-emerald-100 text-emerald-800 ring-emerald-300" : "bg-amber-100 text-amber-800 ring-amber-300" : "bg-white text-slate-500 ring-slate-200"}`}>{children}</button>; }
